// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCOT3oGbO7-26OkgrrnO0Uk3uxED4JpA',
    appId: '1:928768484209:android:3f367f238d70406a568cd0',
    messagingSenderId: '928768484209',
    projectId: 'mynotes-flutter-proj-safa',
    storageBucket: 'mynotes-flutter-proj-safa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1rX1fcCjuGNUaNk5K-cLapXJtqBcuTc',
    appId: '1:928768484209:ios:e9439a81d813de3e568cd0',
    messagingSenderId: '928768484209',
    projectId: 'mynotes-flutter-proj-safa',
    storageBucket: 'mynotes-flutter-proj-safa.appspot.com',
    iosClientId: '928768484209-cat28kvjp0g7r4m5a0pl0j20575i7srd.apps.googleusercontent.com',
    iosBundleId: 'com.safa.mynotes',
  );
}
